---
abstract: 'The great new Logic::Tools!'
author:
  - 'lagutas, C<< <lagutas at gmail.com> >>'
  - 'lagutas <lagutas@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Logic-Tools
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
